package com.hardes.ssm.mapper;

import com.hardes.ssm.pojo.Mybatis3;
import com.hardes.ssm.pojo.Mybatis3Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Mybatis3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    long countByExample(Mybatis3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int deleteByExample(Mybatis3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int insert(Mybatis3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int insertSelective(Mybatis3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    List<Mybatis3> selectByExample(Mybatis3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    Mybatis3 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int updateByExampleSelective(@Param("record") Mybatis3 record, @Param("example") Mybatis3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int updateByExample(@Param("record") Mybatis3 record, @Param("example") Mybatis3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int updateByPrimaryKeySelective(Mybatis3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis3
     *
     * @mbg.generated Wed Oct 30 16:28:23 SGT 2019
     */
    int updateByPrimaryKey(Mybatis3 record);
}