package com.hardes.ssm.pojo;

public class Generator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.user
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.orders
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    private String orders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.orderdetail
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    private String orderdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.items
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    private String items;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.user
     *
     * @return the value of generator.user
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.user
     *
     * @param user the value for generator.user
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.orders
     *
     * @return the value of generator.orders
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public String getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.orders
     *
     * @param orders the value for generator.orders
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public void setOrders(String orders) {
        this.orders = orders == null ? null : orders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.orderdetail
     *
     * @return the value of generator.orderdetail
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public String getOrderdetail() {
        return orderdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.orderdetail
     *
     * @param orderdetail the value for generator.orderdetail
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public void setOrderdetail(String orderdetail) {
        this.orderdetail = orderdetail == null ? null : orderdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.items
     *
     * @return the value of generator.items
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public String getItems() {
        return items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.items
     *
     * @param items the value for generator.items
     *
     * @mbg.generated Wed Oct 30 15:52:46 SGT 2019
     */
    public void setItems(String items) {
        this.items = items == null ? null : items.trim();
    }
}